import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          <div className="container mx-auto px-4">{children}</div>
          <Toaster
            position="top-right"
            richColors
            closeButton={false}
            toastOptions={{
              className: "bg-white text-black shadow-lg",
              style: {
                background: "#fff",
                color: "#000",
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
